In [1]:
import numpy as np
from rnn_utils import *
from funcs import *

In [2]:
np.random.seed(1)
xt = np.random.randn(3,10)
a_prev = np.random.randn(5,10)
parameters = {}
parameters['Waa'] = np.random.randn(5,5)
parameters['Wax'] = np.random.randn(5,3)
parameters['Wya'] = np.random.randn(2,5)
parameters['ba'] = np.random.randn(5,1)
parameters['by'] = np.random.randn(2,1)


In [3]:

# Retrieve parameters from "parameters"
Wax = parameters["Wax"]
Waa = parameters["Waa"]
Wya = parameters["Wya"]
ba = parameters["ba"]
by = parameters["by"]

### START CODE HERE ### (≈2 lines)
# compute next activation state using the formula given above
a_next = np.tanh(Waa @ a_prev + Wax @ xt + ba)
# compute output of the current cell using the formula given above
yt_pred = softmax(Wya @ a_next + by)
### END CODE HERE ###

# store values you need for backward propagation in cache
cache = (a_next, a_prev, xt, parameters)


In [4]:
print("a_next[4] = \n", a_next[4])
print("a_next.shape = \n", a_next.shape)
print("yt_pred[1] =\n", yt_pred[1])
print("yt_pred.shape = \n", yt_pred.shape)


a_next[4] = 
 [ 0.59584544  0.18141802  0.61311866  0.99808218  0.85016201  0.99980978
 -0.18887155  0.99815551  0.6531151   0.82872037]
a_next.shape = 
 (5, 10)
yt_pred[1] =
 [0.9888161  0.01682021 0.21140899 0.36817467 0.98988387 0.88945212
 0.36920224 0.9966312  0.9982559  0.17746526]
yt_pred.shape = 
 (2, 10)


In [5]:
np.random.seed(1)
x = np.random.randn(3,10,4)
a0 = np.random.randn(5,10)
parameters = {}
parameters['Waa'] = np.random.randn(5,5)
parameters['Wax'] = np.random.randn(5,3)
parameters['Wya'] = np.random.randn(2,5)
parameters['ba'] = np.random.randn(5,1)
parameters['by'] = np.random.randn(2,1)



In [6]:


# Initialize "caches" which will contain the list of all caches
caches = []

# Retrieve dimensions from shapes of x and parameters["Wya"]
n_x, m, T_x = x.shape
n_y, n_a = parameters["Wya"].shape

### START CODE HERE ###

# initialize "a" and "y_pred" with zeros (≈2 lines)
a = np.zeros((n_a, m, T_x))
y_pred = np.zeros((n_y, m, T_x))

# Initialize a_next (≈1 line)
a_next = a0

# loop over all time-steps of the input 'x' (1 line)
for t in range(T_x):
    # Update next hidden state, compute the prediction, get the cache (≈2 lines)
    xt = x[:,:,t]
    a_next, yt_pred, cache = rnn_cell_forward(xt, a_next, parameters)
    # Save the value of the new "next" hidden state in a (≈1 line)
    a[:,:,t] = a_next
    # Save the value of the prediction in y (≈1 line)
    y_pred[:,:,t] = yt_pred
    # Append "cache" to "caches" (≈1 line)
    caches.append(cache)

### END CODE HERE ###

# store values needed for backward propagation in cache
caches = (caches, x)


In [7]:


print("a[4][1] = \n", a[4][1])
print("a.shape = \n", a.shape)
print("y_pred[1][3] =\n", y_pred[1][3])
print("y_pred.shape = \n", y_pred.shape)
print("caches[1][1][3] =\n", caches[1][1][3])
print("len(caches) = \n", len(caches))

a[4][1] = 
 [-0.99999375  0.77911235 -0.99861469 -0.99833267]
a.shape = 
 (5, 10, 4)
y_pred[1][3] =
 [0.79560373 0.86224861 0.11118257 0.81515947]
y_pred.shape = 
 (2, 10, 4)
caches[1][1][3] =
 [-1.1425182  -0.34934272 -0.20889423  0.58662319]
len(caches) = 
 2


In [8]:
np.random.seed(1)
xt = np.random.randn(3,10)
a_prev = np.random.randn(5,10)
c_prev = np.random.randn(5,10)
parameters = {}
parameters['Wf'] = np.random.randn(5, 5+3)
parameters['bf'] = np.random.randn(5,1)
parameters['Wi'] = np.random.randn(5, 5+3)
parameters['bi'] = np.random.randn(5,1)
parameters['Wo'] = np.random.randn(5, 5+3)
parameters['bo'] = np.random.randn(5,1)
parameters['Wc'] = np.random.randn(5, 5+3)
parameters['bc'] = np.random.randn(5,1)
parameters['Wy'] = np.random.randn(2,5)
parameters['by'] = np.random.randn(2,1)


In [9]:

# Retrieve parameters from "parameters"
Wf = parameters["Wf"] # forget gate weight
bf = parameters["bf"]
Wi = parameters["Wi"] # update gate weight (notice the variable name)
bi = parameters["bi"] # (notice the variable name)
Wc = parameters["Wc"] # candidate value weight
bc = parameters["bc"]
Wo = parameters["Wo"] # output gate weight
bo = parameters["bo"]
Wy = parameters["Wy"] # prediction weight
by = parameters["by"]

# Retrieve dimensions from shapes of xt and Wy
n_x, m = xt.shape
n_y, n_a = Wy.shape

### START CODE HERE ###
# Concatenate a_prev and xt (≈1 line)
concat = np.vstack((a_prev, xt))

# Compute values for ft (forget gate), it (update gate),
# cct (candidate value), c_next (cell state),
# ot (output gate), a_next (hidden state) (≈6 lines)
ft = sigmoid(Wf @ concat + bf)        # forget gate
it = sigmoid(Wi @ concat + bi)        # update gate
cct = np.tanh(Wc @ concat + bc)       # candidate value
c_next = ft * c_prev + it * cct    # cell state
ot = sigmoid(Wo @ concat + bo)        # output gate
a_next = ot * np.tanh(c_next)    # hidden state

# Compute prediction of the LSTM cell (≈1 line)
yt_pred = softmax(Wy @ a_next + by)
### END CODE HERE ###

# store values needed for backward propagation in cache
cache = (a_next, c_next, a_prev, c_prev, ft, it, cct, ot, xt, parameters)

In [10]:
print("a_next[4] = \n", a_next[4])
print("a_next.shape = ", a_next.shape)
print("c_next[2] = \n", c_next[2])
print("c_next.shape = ", c_next.shape)
print("yt[1] =", yt_pred[1])
print("yt.shape = ", yt_pred.shape)
print("cache[1][3] =\n", cache[1][3])
print("len(cache) = ", len(cache))

a_next[4] = 
 [-0.66408471  0.0036921   0.02088357  0.22834167 -0.85575339  0.00138482
  0.76566531  0.34631421 -0.00215674  0.43827275]
a_next.shape =  (5, 10)
c_next[2] = 
 [ 0.63267805  1.00570849  0.35504474  0.20690913 -1.64566718  0.11832942
  0.76449811 -0.0981561  -0.74348425 -0.26810932]
c_next.shape =  (5, 10)
yt[1] = [0.79913913 0.15986619 0.22412122 0.15606108 0.97057211 0.31146381
 0.00943007 0.12666353 0.39380172 0.07828381]
yt.shape =  (2, 10)
cache[1][3] =
 [-0.16263996  1.03729328  0.72938082 -0.54101719  0.02752074 -0.30821874
  0.07651101 -1.03752894  1.41219977 -0.37647422]
len(cache) =  10


In [11]:
np.random.seed(1)
x = np.random.randn(3,10,7)
a0 = np.random.randn(5,10)
parameters = {}
parameters['Wf'] = np.random.randn(5, 5+3)
parameters['bf'] = np.random.randn(5,1)
parameters['Wi'] = np.random.randn(5, 5+3)
parameters['bi']= np.random.randn(5,1)
parameters['Wo'] = np.random.randn(5, 5+3)
parameters['bo'] = np.random.randn(5,1)
parameters['Wc'] = np.random.randn(5, 5+3)
parameters['bc'] = np.random.randn(5,1)
parameters['Wy'] = np.random.randn(2,5)
parameters['by'] = np.random.randn(2,1)

In [12]:
# Initialize "caches", which will track the list of all the caches
caches = []

### START CODE HERE ###
Wy = parameters['Wy'] # saving parameters['Wy'] in a local variable in case students use Wy instead of parameters['Wy']
# Retrieve dimensions from shapes of x and parameters['Wy'] (≈2 lines)
n_x, m, T_x = x.shape
n_y, n_a = parameters['Wy'].shape

# initialize "a", "c" and "y" with zeros (≈3 lines)
a = np.zeros((n_a, m, T_x))
c = np.zeros((n_a, m, T_x))
y = np.zeros((n_y, m, T_x))

# Initialize a_next and c_next (≈2 lines)
a_next = a0
c_next = np.zeros((n_a, m))

# loop over all time-steps
for t in range(T_x):
    # Get the 2D slice 'xt' from the 3D input 'x' at time step 't'
    xt = x[:,:,t]
    # Update next hidden state, next memory state, compute the prediction, get the cache (≈1 line)
    a_next, c_next, yt, cache = lstm_cell_forward(xt, a_next, c_next, parameters)
    # Save the value of the new "next" hidden state in a (≈1 line)
    a[:,:,t] = a_next
    # Save the value of the next cell state (≈1 line)
    c[:,:,t]  = c_next
    # Save the value of the prediction in y (≈1 line)
    y[:,:,t] = yt
    # Append the cache into caches (≈1 line)
    caches.append(cache)

### END CODE HERE ###

# store values needed for backward propagation in cache
caches = (caches, x)


In [13]:
print("a[4][3][6] = ", a[4][3][6])
print("a.shape = ", a.shape)
print("y[1][4][3] =", y[1][4][3])
print("y.shape = ", y.shape)
print("caches[1][1][1] =\n", caches[1][1][1])
print("c[1][2][1]", c[1][2][1])
print("len(caches) = ", len(caches))

a[4][3][6] =  0.17211776753291672
a.shape =  (5, 10, 7)
y[1][4][3] = 0.9508734618501101
y.shape =  (2, 10, 7)
caches[1][1][1] =
 [ 0.82797464  0.23009474  0.76201118 -0.22232814 -0.20075807  0.18656139
  0.41005165]
c[1][2][1] -0.8555449167181982
len(caches) =  2
